image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080
#    onOpen: open-preview

checkoutLocation: "go/src/github.com/nate-trojian/ccg-game-server"
workspaceLocation: "go/src/github.com/nate-trojian/ccg-game-server"

tasks:
  - init: >
      go get -v ./...
